Q81. Please write a program to shuffle and print the list [3,6,7,8]. 
Hints: Use shuffle() function to shuffle a list

In [8]:
from random import shuffle
listy = [3,6,7,8]
shuffle(listy)
print(listy)

[7, 3, 6, 8]


Q82. Please write a program to generate all sentences where subject is in ["I", "You"] and verb is in ["Play", "Love"] and the object is in ["Hockey","Football"]. 
Hints: Use list[index] notation to get a element from a list.

In [12]:
subjects=["I", "You"]
verbs=["Play", "Love"]
objects=["Hockey","Football"]
for sub in subjects:
    for verb in verbs:
        for obj in objects:
            print("{} {} {}".format(sub,verb,obj))

I Play Hockey
I Play Football
I Love Hockey
I Love Football
You Play Hockey
You Play Football
You Love Hockey
You Love Football


# OR

In [11]:
import itertools
subject = ["I", "You"]
verb = ["Play", "Love"]
objects = ["Hockey","Football"]

sentence = [subject, verb, objects]
n = list(itertools.product(*sentence))
for i in n: 
    print(i)

('I', 'Play', 'Hockey')
('I', 'Play', 'Football')
('I', 'Love', 'Hockey')
('I', 'Love', 'Football')
('You', 'Play', 'Hockey')
('You', 'Play', 'Football')
('You', 'Love', 'Hockey')
('You', 'Love', 'Football')


Q83. Please write a program to print the list after removing delete even numbers in [5,6,77,45,22,12,24]. 
Hints: Use list comprehension to delete a bunch of element from a list.

In [15]:
listy = [5,6,77,45,22,12,24]
li = [x for x in listy if x%2!=0]
print(li)

[5, 77, 45]


Q84.  By using list comprehension, please write a program to print the list after removing delete numbers which are divisible by 5 and 7 in [12,24,35,70,88,120,155]. 
Hints: Use list comprehension to delete a bunch of element from a list. 

In [16]:
listy = [12,24,35,70,88,120,155]
li = [x for x in listy if x%5!=0 and x%7!=0]
print(li)

[12, 24, 88]


Q85. By using list comprehension, please write a program to print the list after removing the 0th, 2nd, 4th,6th numbers in [12,24,35,70,88,120,155]. 
Hints: Use list comprehension to delete a bunch of element from a list. Use enumerate() to get (index, value) tuple. 

In [19]:
listy = [12,24,35,70,88,120,155]
ind = [0,2,4,6]
new_list = [i for (j, i) in enumerate(listy) if j not in ind]
print(new_list)

[24, 70, 120]


Q86. By using list comprehension, please write a program generate a 3*5*8 3D array whose each element is 0. 
Hints: Use list comprehension to make an array. 

In [21]:
array = [[ [0 for col in range(8)] for col in range(5)] for row in range(3)]
print (array)

[[[0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0]], [[0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0]], [[0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0]]]


Q87. By using list comprehension, please write a program to print the list after removing the 0th,4th,5th numbers in [12,24,35,70,88,120,155]. 
Hints: Use list comprehension to delete a bunch of element from a list. Use enumerate() to get (index, value) tuple.

In [26]:
listy = [12,24,35,70,88,120,155]
ind = [0,4,5]
new_list = [i for (j, i) in enumerate(listy) if j not in ind]
print(new_list)

[24, 35, 70, 155]


Q88. By using list comprehension, please write a program to print the list after removing the value 24 in [12,24,35,24,88,120,155]. 
Hints: Use list's remove method to delete a value. 

In [29]:
listy = [12,24,35,24,88,120,155]
listy.remove(24) #this will remove 24 only for the first time
listy.remove(24) #used to delete 24 for the second time
print(listy)

[12, 35, 88, 120, 155]


Q89. With two given lists [1,3,6,78,35,55] and [12,24,35,24,88,120,155], write a program to make a list whose elements are intersection of the above given lists. 
Hints: Use set() and "&=" to do set intersection operation.

In [30]:
set1=set([1,3,6,78,35,55])
set2=set([12,24,35,24,88,120,155])
set1 &= set2
li=list(set1)
print (li)

[35]


Q90. With a given list [12, 24, 35, 24, 88, 120, 155, 88, 120, 155], write a program to print this list after removing all duplicate values with original order reserved. 
Hints: Use set() to store a number of values without duplicate.

In [34]:
listy = [12, 24, 35, 24, 88, 120, 155, 88, 120, 155]
set1 = set(listy)
print(set1)

{35, 12, 155, 24, 88, 120}
